let DEMO_DATA={};
const TAB_NAMES=["Athlete_Profile", "Testing_Sessions", "Performance_Metrics", "Normative_Data", "Coach_Recommendations", "Areas_of_Focus", "Next_Steps", "Dashboard_Settings", "Recommendation Matrix", "Status Logic", "RVX App Programs", "Dashboard Lookup Guide", "Dropdown_Lists", "Recommendation_Output", "Recommendation_Lookup"];
let appData={}; let selectedAthleteId=null;
const el = id => document.getElementById(id);
const clean = value => value === null || value === undefined ? '' : String(value).trim();
const num = value => { const parsed = Number(value); return Number.isFinite(parsed) ? parsed : 0; };
const parseDate = value => { if(value instanceof Date) return value; const match=clean(value).match(/^Date\((\d+),(\d+),(\d+)\)$/); if(match) return new Date(+match[1],+match[2],+match[3]); const dateObj=new Date(value); return Number.isNaN(dateObj.getTime())?null:dateObj; };
const formatDate = value => { const dateObj=parseDate(value); return dateObj?dateObj.toLocaleDateString('en-CA',{month:'short',day:'numeric',year:'numeric'}).toUpperCase():'—'; };
const ageOn = (birthValue, referenceValue) => { const birthObj=parseDate(birthValue), refObj=parseDate(referenceValue)||new Date(); if(!birthObj)return null; let ageVal=refObj.getFullYear()-birthObj.getFullYear(); const monthDelta=refObj.getMonth()-birthObj.getMonth(); if(monthDelta<0||(monthDelta===0&&refObj.getDate()<birthObj.getDate()))ageVal--; return ageVal; };
const erf = x => { const sign=x>=0?1:-1; x=Math.abs(x); const a1=.254829592,a2=-.284496736,a3=1.421413741,a4=-1.453152027,a5=1.061405429,p=.3275911; const t=1/(1+p*x); return sign*(1-(((((a5*t+a4)*t)+a3)*t+a2)*t+a1)*t*Math.exp(-x*x)); };
const normalCdf = z => .5*(1+erf(z/Math.sqrt(2)));
const percentileFor = (value, normRow, direction) => { if(!normRow||!num(normRow.std_dev)) return 50; let z=(num(value)-num(normRow.mean))/num(normRow.std_dev); if(direction==='lower')z=-z; return Math.max(1,Math.min(99,Math.round(normalCdf(z)*100))); };
const formatValue = (value, unit) => { const valueNum=num(value); if(unit==='sec')return valueNum.toFixed(2); if(Math.abs(valueNum)>=1000)return valueNum.toLocaleString('en-CA',{maximumFractionDigits:0}); return valueNum.toLocaleString('en-CA',{maximumFractionDigits:1}); };
const iconFor = category => ({'Acceleration':'⚡','Movement':'↕','Strength & Power':'◆','Agility':'◇'}[category]||'●');
function rows(tab){return appData[tab]||[]}
function recommendationRows(){return rows('Recommendation_Output').filter(row=>clean(row['Athlete ID'])===selectedAthleteId).sort((a,b)=>{const rank={'Below Norm':0,'Equal to Norm':1,'Above Norm':2};return (rank[clean(a['Final Status'])]??3)-(rank[clean(b['Final Status'])]??3);});}
function uniqueValues(values){return [...new Set(values.map(clean).filter(Boolean))];}
function getAthlete(){return rows('Athlete_Profile').find(row=>clean(row.athlete_id)===selectedAthleteId)||rows('Athlete_Profile')[0]||{}}
function latestMetrics(){ const athleteRows=rows('Performance_Metrics').filter(row=>clean(row.athlete_id)===selectedAthleteId); const grouped={}; athleteRows.forEach(row=>(grouped[row.metric_key]??=[]).push(row)); return Object.values(grouped).map(group=>group.sort((a,b)=>parseDate(a.test_date)-parseDate(b.test_date))); }
function matchingNorm(metricRow, athleteRow, refDate){ const athleteAge=ageOn(athleteRow.birth_date,refDate); return rows('Normative_Data').find(norm=>clean(norm.metric_key)===clean(metricRow.metric_key)&&clean(norm.sport).toLowerCase()===clean(athleteRow.sport).toLowerCase()&&(!clean(norm.sex)||clean(norm.sex).toLowerCase()===clean(athleteRow.sex).toLowerCase())&&(athleteAge===null||(athleteAge>=num(norm.age_min)&&athleteAge<=num(norm.age_max)))); }
function render(){
  const athletes=rows('Athlete_Profile'); if(!selectedAthleteId||!athletes.some(row=>clean(row.athlete_id)===selectedAthleteId)) selectedAthleteId=clean(athletes[0]?.athlete_id);
  el('athleteSelect').innerHTML=athletes.map(row=>`<option value="${clean(row.athlete_id)}" ${clean(row.athlete_id)===selectedAthleteId?'selected':''}>${clean(row.first_name)} ${clean(row.last_name)}</option>`).join('');
  const athleteRow=getAthlete(); const metricGroups=latestMetrics(); const allDates=metricGroups.flat().map(row=>parseDate(row.test_date)).filter(Boolean).sort((a,b)=>a-b); const firstDate=allDates[0],lastDate=allDates.at(-1);
  el('dateRange').textContent=firstDate&&lastDate?`${formatDate(firstDate)} – ${formatDate(lastDate)}`:'—';
  const initials=`${clean(athleteRow.first_name)[0]||''}${clean(athleteRow.last_name)[0]||''}`;
  const heightFt=num(athleteRow.height_cm)?`${Math.floor(num(athleteRow.height_cm)/30.48)}′ ${Math.round((num(athleteRow.height_cm)/2.54)%12)}″`:'';
  const weightLb=num(athleteRow.weight_kg)?Math.round(num(athleteRow.weight_kg)*2.20462):'';
  el('profilePanel').innerHTML=`<div class="athlete-name">${clean(athleteRow.first_name)} ${clean(athleteRow.last_name)}</div><div class="profile-flex"><div class="avatar">${clean(athleteRow.photo_url)?`<img src="${clean(athleteRow.photo_url)}">`:`<span>${initials}</span>`}</div><div class="details"><label>Athlete ID</label><b>${clean(athleteRow.athlete_id)}</b><label>Age</label><b>${ageOn(athleteRow.birth_date,lastDate)||'—'}</b><label>Birth Year</label><b>${parseDate(athleteRow.birth_date)?.getFullYear()||'—'}</b><label>Sport</label><b>${clean(athleteRow.sport)}</b><label>Team</label><b>${clean(athleteRow.team)}</b><label>Position</label><b>${clean(athleteRow.position)}</b><label>Dominance</label><b>${clean(athleteRow.hand_dominance)}</b><label>Height</label><b>${heightFt} (${num(athleteRow.height_cm)} cm)</b><label>Weight</label><b>${weightLb} lb (${num(athleteRow.weight_kg)} kg)</b></div></div>`;
  const percentiles=[];
  el('metricsBody').innerHTML=metricGroups.map(group=>{ const first=group[0],latest=group.at(-1); const direction=clean(latest.direction)||'higher'; const rawChange=num(latest.value)-num(first.value); const improvement=direction==='lower'?-rawChange:rawChange; const pctBase=num(first.value)||1; const pctImprovement=(improvement/pctBase)*100; const normRow=matchingNorm(latest,athleteRow,latest.test_date); const percentile=percentileFor(latest.value,normRow,direction); percentiles.push(percentile); const statusClass=improvement>=0?'':'watch'; return `<tr><td><div class="metric-name"><span class="metric-icon">${iconFor(clean(latest.category))}</span>${clean(latest.metric_name)}</div></td><td class="best">${formatValue(latest.value,latest.unit)}</td><td>${clean(latest.unit)}</td><td class="delta ${improvement>=0?'good':'bad'}">${rawChange>0?'+':''}${formatValue(rawChange,latest.unit)} ${improvement>=0?'▲':'▼'}</td><td class="delta ${improvement>=0?'good':'bad'}">${pctImprovement>0?'+':''}${pctImprovement.toFixed(1)}%</td><td><span class="status ${statusClass}">${improvement>0?'Improved':improvement===0?'Stable':'Watch'}</span></td><td><b>${percentile}<sup>${percentile%10===1&&percentile!==11?'st':percentile%10===2&&percentile!==12?'nd':percentile%10===3&&percentile!==13?'rd':'th'}</sup></b></td></tr>`; }).join('');
  const score=percentiles.length?Math.round(percentiles.reduce((sumVal,item)=>sumVal+item,0)/percentiles.length):0; const label=score>=90?'Elite':score>=75?'Very Good':score>=60?'Above Average':score>=40?'Average':'Developing';
  el('scorePanel').innerHTML=`<div class="score-top"><div class="score-num">${score}<span>%</span></div><div class="score-label"><strong>${label}</strong><small>vs normative data</small></div></div><div class="score-note">Composite score calculated from metric percentiles matched by sport, sex and age range.</div><div class="gauge-labels"><span>0%</span><span>25%</span><span>50%</span><span>75%</span><span>100%</span></div><div class="gauge"><span class="gauge-marker" style="left:calc(${score}% - 2px)"></span></div><div class="score-explain"><b>What this means</b><p>You performed better than approximately ${score}% of athletes represented by the matching normative dataset. Replace the demo norms with validated sport-specific data before making selection or clinical decisions.</p></div>`;
  const sessions=rows('Testing_Sessions').filter(row=>clean(row.athlete_id)===selectedAthleteId).sort((a,b)=>parseDate(a.test_date)-parseDate(b.test_date));
  el('sessionsPanel').innerHTML=sessions.map((row,index)=>`<div class="session"><span class="number-badge">${index+1}</span><div><div class="session-date">${formatDate(row.test_date)}</div><small style="color:#777">${clean(row.session_label)}</small></div></div>`).join('')||'<p>No sessions found.</p>';
  const recommendationOutput=recommendationRows();
  const legacyRecs=rows('Coach_Recommendations').filter(row=>clean(row.athlete_id)===selectedAthleteId&&clean(row.recommendation)).sort((a,b)=>num(a.display_order)-num(b.display_order));
  el('recommendationsPanel').innerHTML=recommendationOutput.length?recommendationOutput.map(row=>`<div class="recommendation"><span class="rec-icon">${clean(row['Final Status'])==='Below Norm'?'!':clean(row['Final Status'])==='Above Norm'?'✓':'→'}</span><div class="rec-content"><strong>${clean(row['Metric Name'])} · ${clean(row['Final Status'])}</strong><p>${clean(row['Final Coach Recommendation'])||clean(row['Auto Coach Recommendation'])}</p></div></div>`).join(''):legacyRecs.map(row=>`<div class="recommendation"><span class="rec-icon">${iconFor(clean(row.category))}</span><div class="rec-content"><strong>${clean(row.title)}</strong><p>${clean(row.recommendation)}</p></div></div>`).join('')||'<p>No recommendations found.</p>';
  const outputFocuses=uniqueValues(recommendationOutput.flatMap(row=>[row['Final Area of Focus'],row['Secondary Areas of Focus']]));
  const legacyFocuses=rows('Areas_of_Focus').filter(row=>clean(row.athlete_id)===selectedAthleteId&&clean(row.focus_area)).sort((a,b)=>num(a.display_order)-num(b.display_order)).map(row=>row.focus_area);
  const focusValues=outputFocuses.length?outputFocuses:legacyFocuses;
  el('focusPanel').innerHTML=focusValues.slice(0,8).map(value=>`<div class="focus"><span class="check-badge">✓</span><span>${clean(value)}</span></div>`).join('')||'<p>No focus areas found.</p>';
  const primaryPrograms=uniqueValues(recommendationOutput.map(row=>row['Final RVX App Program']||row['Primary RVX App Program']));
  const secondaryPrograms=uniqueValues(recommendationOutput.map(row=>row['Secondary RVX App Program']));
  const coachingCues=uniqueValues(recommendationOutput.map(row=>row['Coaching Cue']));
  const retestGuidance=uniqueValues(recommendationOutput.map(row=>row['Retest Guidance']));
  const legacySteps=rows('Next_Steps').filter(row=>clean(row.athlete_id)===selectedAthleteId&&clean(row.next_step)).sort((a,b)=>num(a.display_order)-num(b.display_order)).map(row=>row.next_step);
  const comments=rows('Dashboard_Settings').find(row=>clean(row.setting)==='coach_comments')?.value||'';
  let stepsHtml='';
  primaryPrograms.slice(0,4).forEach((value,index)=>stepsHtml+=`<div class="step"><span class="check-badge">${index+1}</span><span><b>${clean(value)}</b><br><small style="color:#999">Primary RVX app program</small></span></div>`);
  secondaryPrograms.slice(0,2).forEach(value=>stepsHtml+=`<div class="step"><span class="check-badge">+</span><span>${clean(value)}<br><small style="color:#999">Secondary program</small></span></div>`);
  if(!stepsHtml)legacySteps.forEach((value,index)=>stepsHtml+=`<div class="step"><span class="check-badge">${index+1}</span><span>${clean(value)}</span></div>`);
  if(coachingCues[0])stepsHtml+=`<div class="comments"><strong>Coaching cue</strong><p>${clean(coachingCues[0])}</p></div>`;
  if(retestGuidance[0])stepsHtml+=`<div class="comments"><strong>Retest guidance</strong><p>${clean(retestGuidance[0])}</p></div>`;
  if(comments)stepsHtml+=`<div class="comments"><strong>Coach comments</strong><p>${clean(comments)}</p></div>`;
  el('stepsPanel').innerHTML=stepsHtml||'<p>No programs or next steps found.</p>';
  el('chartsGrid').innerHTML=metricGroups.map(group=>buildChart(group,athleteRow)).join('');
  applySettings();
}
function buildChart(group,athleteRow){ const values=group.map(row=>num(row.value)); const latest=group.at(-1); const normRow=matchingNorm(latest,athleteRow,latest.test_date); const normValue=normRow?num(normRow.mean):null; const allValues=normValue===null?values:[...values,normValue]; let minVal=Math.min(...allValues),maxVal=Math.max(...allValues); const pad=(maxVal-minVal||1)*.2; minVal-=pad;maxVal+=pad; const w=300,h=130,left=30,right=10,top=12,bottom=22; const xAt=index=>left+(index*(w-left-right)/Math.max(1,group.length-1)); const yAt=value=>top+(maxVal-value)*(h-top-bottom)/(maxVal-minVal); const athletePath=values.map((value,index)=>`${index?'L':'M'}${xAt(index)},${yAt(value)}`).join(' '); const normPath=normValue===null?'':`M${left},${yAt(normValue)} L${w-right},${yAt(normValue)}`; const gridLines=[0,.5,1].map(frac=>{const y=top+frac*(h-top-bottom);const value=maxVal-frac*(maxVal-minVal);return `<line x1="${left}" y1="${y}" x2="${w-right}" y2="${y}" class="chart-grid"/><text x="2" y="${y+3}" fill="#777" font-size="9">${formatValue(value,latest.unit)}</text>`}).join(''); const points=values.map((value,index)=>`<circle cx="${xAt(index)}" cy="${yAt(value)}" r="4" class="athlete-point"/><text x="${xAt(index)}" y="${h-4}" fill="#777" font-size="9" text-anchor="middle">${index+1}</text>`).join(''); return `<div class="chart-panel"><div class="chart-title">${clean(latest.metric_name)} (${clean(latest.unit)})</div><div class="chart-meta">Athlete vs matched norm mean</div><svg viewBox="0 0 ${w} ${h}" role="img" aria-label="${clean(latest.metric_name)} trend">${gridLines}<line x1="${left}" y1="${top}" x2="${left}" y2="${h-bottom}" class="chart-axis"/><path d="${normPath}" class="norm-line"/><path d="${athletePath}" class="athlete-line"/>${points}</svg><div class="legend"><span><i></i>Athlete</span><span class="norm"><i></i>Norm mean</span></div></div>`; }
function applySettings(){ const settings={}; rows('Dashboard_Settings').forEach(row=>settings[clean(row.setting)]=row.value); if(settings.accent_color)document.documentElement.style.setProperty('--accent',settings.accent_color); el('orgName').textContent=settings.organization_name||'Performance'; el('reportTitle').textContent=settings.report_title||'Athlete Testing Report'; el('generatedDate').textContent=`Generated ${new Date().toLocaleDateString('en-CA',{month:'short',day:'numeric',year:'numeric'})}`; }
function parseGviz(text){ const start=text.indexOf('{'),end=text.lastIndexOf('}'); if(start<0||end<0)throw new Error('Unexpected Google Sheets response. Confirm the sheet is public.'); const payload=JSON.parse(text.slice(start,end+1)); const cols=payload.table.cols.map((col,index)=>clean(col.label)||`column_${index+1}`); return payload.table.rows.map(row=>{const result={};cols.forEach((column,index)=>{const cell=row.c?.[index];result[column]=cell?.v??''});return result;}); }
function extractSheetId(value){ const match=clean(value).match(/\/spreadsheets\/d\/([a-zA-Z0-9-_]+)/); return match?match[1]:clean(value); }
async function connectSheet(){ const sheetId=extractSheetId(el('sheetIdInput').value); if(!sheetId){el('connectionError').textContent='Enter a Google Sheet URL or ID.';return;} el('connectionError').textContent='Loading tabs…'; el('connectButton').disabled=true; try{ const fetched={}; for(const tabName of TAB_NAMES){ const url=`https://docs.google.com/spreadsheets/d/${sheetId}/gviz/tq?tqx=out:json&sheet=${encodeURIComponent(tabName)}&_=${Date.now()}`; const response=await fetch(url); if(!response.ok)throw new Error(`${tabName} returned ${response.status}`); fetched[tabName]=parseGviz(await response.text()); } appData=fetched; localStorage.setItem('athleteDashboardSheetId',sheetId); selectedAthleteId=null; setConnection(true); render(); closeModal(); }catch(error){el('connectionError').textContent=`Could not load the sheet. Make it public/published and verify all tab names. ${error.message}`;}finally{el('connectButton').disabled=false;} }
function setConnection(isLive){ el('statusDot').classList.toggle('live',isLive); el('connectionText').textContent=isLive?'Google Sheet Connected':'Connect Google Sheet'; el('dataSourceLabel').textContent=isLive?'Live Google Sheet · 15 connected tabs':'Embedded workbook · 50 athletes'; }
function closeModal(){el('settingsModal').classList.remove('open')}
el('openSettings').addEventListener('click',()=>el('settingsModal').classList.add('open'));el('closeSettings').addEventListener('click',closeModal);el('connectButton').addEventListener('click',connectSheet);el('demoButton').addEventListener('click',()=>{appData=structuredClone(DEMO_DATA);localStorage.removeItem('athleteDashboardSheetId');selectedAthleteId=null;setConnection(false);render();closeModal()});el('athleteSelect').addEventListener('change',event=>{selectedAthleteId=event.target.value;render()});el('settingsModal').addEventListener('click',event=>{if(event.target===el('settingsModal'))closeModal()});
async function initializeApp(){try{const r=await fetch('data/demo-data.json',{cache:'no-store'});if(!r.ok)throw new Error(r.status);DEMO_DATA=await r.json();appData=structuredClone(DEMO_DATA)}catch(e){console.error(e);appData={}}const id=localStorage.getItem('athleteDashboardSheetId');if(id){el('sheetIdInput').value=id;setConnection(false);render();await connectSheet()}else{setConnection(false);render()}}initializeApp();
